### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by geek** [hapijs/b64#10]

**Comment by NimmiW** [comment]
hi, I would like to take part in documenting

**Comment by geek** [comment]
@NimmiW thank you, a pull request will be welcomed!

**Comment by NimmiW** [comment]
sure, What part should be documented?, I need some guide

**Comment by NimmiW** [comment]
sure, What part should be documented?, I need some guide, it seems no documentation was integrated so far, I am right?
I prepared a API.md - is this the start of the documentation? I would like to know more since I am a beginner.
https://github.com/NimmiW/b64/blob/doc/API.md

If this is what you expect to be startted, Shall I proceed :)

**Comment by geek** [comment]
@NimmiW I apologize, I should have closed this issue long ago with this commit https://github.com/hapijs/b64/commit/11ee4ad27670bd62089498cd79e3d6d59981f8bd

More issues that are looking for help are on https://hapijs.com/contribute
